#!/usr/bin/env bash
# TubeForge Lite (Go) — regenerates assets/aria2-<target>.gz and the
# build-tagged aria2_bundle_<target>.go from vendor/ binaries.
#   scripts/gen-bundle.sh windows|linux|all
# Missing vendor binary => neutral placeholder (empty gzip, no sha pin), so a
# fresh clone still builds — exactly like the Deno build's --platform none.
set -euo pipefail
cd "$(dirname "$0")/.."
mkdir -p assets

gen() { # <target> <src>
  local target="$1" src="$2" sha="" ver=""
  if [ -f "$src" ]; then
    gzip -9 -c "$src" > "assets/aria2-${target}.gz"
    sha="$(sha256sum "$src" | cut -d' ' -f1)"
    ver="1.37.0"
    local raw_gz
    raw_gz=$(stat -c%s "assets/aria2-${target}.gz")
    echo "[gen-bundle] ${target}: ${src} gz=${raw_gz} bytes sha=${sha}"
  else
    : | gzip -9 -c > "assets/aria2-${target}.gz"
    echo "[gen-bundle] ${target}: PLACEHOLDER (no vendor binary at ${src})"
  fi

  local tag="!windows"
  if [ "$target" = "windows" ]; then tag="windows"; fi
  cat > "aria2_bundle_${target}.go" <<EOF
//go:build ${tag}

// Code generated by scripts/gen-bundle.sh — do not edit by hand.
// Embeds the gzipped aria2c for the $(echo "$target" | tr 'a-z' 'A-Z') build target.
package main

import _ "embed"

//go:embed assets/aria2-${target}.gz
var aria2Gz []byte

const aria2Platform = "${target}"
const aria2Version = "${ver:-}"
const aria2Sha256 = "${sha}"
EOF
}

case "${1:-all}" in
  windows) gen windows vendor/aria2c.exe ;;
  linux)   gen linux   vendor/aria2c-linux ;;
  all)     gen windows vendor/aria2c.exe; gen linux vendor/aria2c-linux ;;
  *) echo "usage: gen-bundle.sh windows|linux|all" >&2; exit 1 ;;
esac
