// Generates src/aria2-bundle.ts — embeds ONE gzipped aria2c binary per build
// target so the compiled exe is fully self-contained (lightweight: gzip keeps
// the payload ~40% of the raw binary; integrity pinned by sha256).
//
//   deno run -A scripts/gen-aria2-bundle.ts --platform linux|windows|none
//
// Binary sources (first hit wins):
//   linux   vendor/aria2c-linux  ../download/tubeforge-desktop/win-tools/aria2c
//   windows vendor/aria2c.exe    ../vendor-tools/aria2c.exe
import proc from "node:process";
import { gzipSync } from "node:zlib";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { createHash } from "node:crypto";

function arg(name: string): string | undefined {
  const i = proc.argv.indexOf(name);
  return i >= 0 ? proc.argv[i + 1] : undefined;
}

function b64(buf: Buffer): string {
  let out = "";
  // Chunk length MUST be a multiple of 3: btoa pads its own output with '=',
  // so a non-3-aligned chunk injects mid-stream padding and corrupts the
  // concatenated base64 (manifested as "unexpected end of file" on gunzip at
  // first-run self-extract). 3-aligned chunks pad only the FINAL chunk.
  const CH = 3 * 0x2000;
  for (let i = 0; i < buf.length; i += CH) {
    out += btoa(String.fromCharCode(...buf.subarray(i, i + CH)));
  }
  return out;
}

async function detectVersion(path: string, platform: string): Promise<string> {
  try {
    const c = new Deno.Command(path, { args: ["--version"], stdout: "piped", stderr: "piped" });
    const { stdout } = await c.output();
    const m = new TextDecoder().decode(stdout).match(/aria2 version ([\d.]+)/);
    if (m) return m[1];
  } catch { /* windows binary on linux can't run — fall back */ }
  return platform === "windows" ? "1.37.0" : "unknown";
}

const platform = arg("--platform") ?? "none";
let linuxB64 = "", winB64 = "", linuxSha = "", winSha = "", version = "";

if (platform !== "none") {
  const table: Record<string, string[]> = {
    linux: ["vendor/aria2c-linux", "../download/tubeforge-desktop/win-tools/aria2c"],
    windows: ["vendor/aria2c.exe", "../vendor-tools/aria2c.exe"],
  };
  const candidates = table[platform];
  if (!candidates) {
    console.error(`unknown --platform '${platform}' (linux|windows|none)`);
    proc.exit(1);
  }
  const src = candidates.find((p) => existsSync(p));
  if (!src) {
    console.error(`no aria2c binary found for ${platform}; tried: ${candidates.join(", ")}`);
    console.error("run scripts/fetch-aria2.sh first, or pass --platform none for a PATH-only build");
    proc.exit(1);
  }
  const raw = readFileSync(src);
  version = await detectVersion(src, platform);
  const gz = gzipSync(raw, { level: 9 });
  if (platform === "linux") {
    linuxB64 = b64(gz);
    linuxSha = createHash("sha256").update(raw).digest("hex");
  } else {
    winB64 = b64(gz);
    winSha = createHash("sha256").update(raw).digest("hex");
  }
  console.log(
    `[gen-bundle] ${platform}: ${src} raw=${(raw.length / 1048576).toFixed(1)}MiB gz=${(gz.length / 1048576).toFixed(1)}MiB b64=${((gz.length * 4) / 3 / 1048576).toFixed(1)}MiB v${version}`,
  );
}

const bundle = linuxB64
  ? { b64: linuxB64, platform: "linux", sha: linuxSha }
  : winB64
  ? { b64: winB64, platform: "windows", sha: winSha }
  : { b64: "", platform: "none", sha: "" };

const out = `// AUTO-GENERATED by scripts/gen-aria2-bundle.ts — do not edit by hand.
// target=${bundle.platform} aria2=${version || "-"}
export const ARIA2_GZ_B64: string | null = ${bundle.b64 ? `"${bundle.b64}"` : "null"};
export const ARIA2_PLATFORM = "${bundle.platform}";
export const ARIA2_VERSION = "${version}";
export const ARIA2_SHA256 = "${bundle.sha}";
`;
writeFileSync(new URL("../src/aria2-bundle.ts", import.meta.url), out);
console.log(`[gen-bundle] wrote src/aria2-bundle.ts (target=${bundle.platform})`);
