//go:build !windows

// Code generated by scripts/gen-bundle.sh — do not edit by hand.
// Embeds the gzipped aria2c for the LINUX build target.
package main

import _ "embed"

//go:embed assets/aria2-linux.gz
var aria2Gz []byte

const aria2Platform = "linux"
const aria2Version = "1.37.0"
const aria2Sha256 = "80e577dc58348b96da46dd12d326bc99794b5021be395a3e890f2d67c8790c22"
