// TubeForge Lite (Go) — embedded aria2 support.
//
// The build-time bundle (aria2_bundle_*.go, generated by scripts/gen-bundle.sh)
// carries ONE gzipped aria2c binary for the compile target. On first run it is
// extracted to <dataDir>/bin/ and the bin dir is PREPENDED to PATH so the
// (untouched) engine tool resolution finds it via the normal PATH candidate.
package main

import (
	"bytes"
	"compress/gzip"
	"crypto/sha256"
	"encoding/hex"
	"io"
	"os"
	"path/filepath"
	"runtime"
	"strings"
)

func aria2BundleInfo() Aria2BundleInfo {
	return Aria2BundleInfo{
		Bundled:  len(aria2Gz) > 0,
		Platform: aria2Platform,
		Version:  aria2Version,
		Sha256:   aria2Sha256,
	}
}

// ensureBundledAria2 extracts the bundled aria2c (idempotent, sha256-verified)
// and makes it visible on PATH. Safe to call at every startup; writes only
// when the binary is missing.
func ensureBundledAria2(dataDir string) EnsureResult {
	if len(aria2Gz) == 0 {
		return EnsureResult{Extracted: false, Path: nil}
	}
	binDir := filepath.Join(dataDir, "bin")
	name := "aria2c"
	if runtime.GOOS == "windows" {
		name = "aria2c.exe"
	}
	p := filepath.Join(binDir, name)
	if _, err := os.Stat(p); os.IsNotExist(err) {
		zr, err := gzip.NewReader(bytes.NewReader(aria2Gz))
		if err != nil {
			return EnsureResult{Extracted: false, Error: "aria2 bundle is not valid gzip: " + err.Error()}
		}
		raw, err := io.ReadAll(zr)
		zr.Close()
		if err != nil {
			return EnsureResult{Extracted: false, Error: "aria2 bundle decompress failed: " + err.Error()}
		}
		if len(raw) == 0 {
			return EnsureResult{Extracted: false, Error: "aria2 bundle is empty (placeholder build)"}
		}
		// integrity: refuse to install a corrupted payload
		if aria2Sha256 != "" {
			sum := sha256.Sum256(raw)
			got := hex.EncodeToString(sum[:])
			if got != strings.ToLower(aria2Sha256) {
				return EnsureResult{Extracted: false, Error: "aria2 bundle sha256 mismatch"}
			}
		}
		if err := os.MkdirAll(binDir, 0o755); err != nil {
			return EnsureResult{Extracted: false, Error: err.Error()}
		}
		if err := os.WriteFile(p, raw, 0o755); err != nil {
			return EnsureResult{Extracted: false, Error: err.Error()}
		}
	}
	// prepend binDir to PATH (dedup)
	pth := os.Getenv("PATH")
	sep := ":"
	if runtime.GOOS == "windows" {
		sep = ";"
	}
	for _, d := range filepath.SplitList(pth) {
		if d == binDir {
			return EnsureResult{Extracted: true, Path: &p}
		}
	}
	os.Setenv("PATH", binDir+sep+pth)
	return EnsureResult{Extracted: true, Path: &p}
}
