//go:build windows

// Code generated by scripts/gen-bundle.sh — do not edit by hand.
// Embeds the gzipped aria2c for the WINDOWS build target.
package main

import _ "embed"

//go:embed assets/aria2-windows.gz
var aria2Gz []byte

const aria2Platform = "windows"
const aria2Version = "1.37.0"
const aria2Sha256 = "be2099c214f63a3cb4954b09a0becd6e2e34660b886d4c898d260febfe9d70c2"
